export const addTarea = {
    btn_menu_hamburguesa: 'button.qa-main-menu-btn',
    btn_tareas: '.MuiListItem-root.qa-item-menu-sidebar[role="button"]:contains("Tareas")',
    btn_plan_de_tareas: 'h6.MuiTypography-root.MuiTypography-subtitle1.MuiListItemText-primary:contains("Plan de Tareas")',
    txt_plan_de_tareas: 'h1.MuiTypography-root.MuiTypography-subtitle1.css-yu03l4:contains("Plan de Tareas")',
    btn_agregar_tarea: 'button[aria-label="Agregar"]',
    txt_datos_requeridos: '.qa-alert-error',
    descripcion: 'input',
    btn_guardar: 'button.qa-btn-save-details:contains("Guardar")',
    popup_creacion_exitosa: 'div[role="alert"] #notistack-snackbar:contains("Proceso Realizado")',
    btn_add_tarea_: 'div.qa-item-menu-tabdetails:contains("Tareas")',
    btn_add_tarea_2: '.qa-button-add-task[aria-label="Agregar tarea"]',
    input_descripcion: 'input',
    btn_tipo_de_tarea: 'input.MuiOutlinedInput-input[readonly][aria-describedby$="-helper-text"]',
    seleccionar_tipo_de_tarea: 'li.MuiListItem-root h2:contains("Mantenimiento")',
    input_tiempo_paro_mtto: 'input',
    btn_agregar_activador: 'button[aria-label="SpeedDial"]',
    btn_agregar_activador_evento: 'button.qa-date-trigger[aria-label="Agregar Activador Fecha"]',
    btn_guardar_activador_evento_fecha: 'button.qa-save-btn.qa-save-btn-trigger.icon_button[aria-label="Guardar"]',
    btn_guardar_tarea: 'div.MuiToolbar-root div.MuiBox-root.css-0 > button.qa-save-btn.icon_button[aria-label="Guardar"]',
    icono_flecha_izquierda: 'button.qa-btn-back-drawer svg[data-info="full_arrow_left"]',
    tabla_tareas: '.MuiTableRow-root.qa-item-table0',
    validar_tarea_creada: (nombreTarea) => '.MuiTableRow-root.qa-item-table0:contains("' + nombreTarea + '")',
    btn_clonar_tarea: 'button.qa-copy[aria-label="Clonar Tarea"]',
    //activos vinculados
    btn_activos_viculados: '.qa-item-menu-tabdetails:contains("Activos Vinculados")',
    btn_agregar_activos_viculados: '.qa-link-assets-btn svg[data-testid="AddIcon"]',
    btn_buscar_activos: 'button.qa-btn-search-global[aria-label="Buscar..."]',
    txt_buscar_activos: 'input[placeholder*="buscar"], input[placeholder*="Buscar"], input[type="search"]',
    // Selectores para buscar y seleccionar activos específicos
    buscar_activo_por_codigo: (codigo) => `*:contains("${codigo}")`,
    buscar_activo_por_nombre: (nombre) => `*:contains("${nombre}")`,
    tabla_activos_disponibles: '.qa-list-item',
    btn_confirmar_seleccion: 'button:contains("Confirmar")',
    btn_vincular_activos: 'button.qa-btn-associate-asset[aria-label="Vincular Activos e Iniciar tareas"]',
}